apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    environment: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      environment: {{ .Values.namespace }}
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - {}